generic = [	'{new0}Uqbar',
		'{new0}Tlon',
		'{new0}Orbis',
		'Null {number}',
		'{new0}Brittia',
		'{new0}Coral',
		'{new0}Eureka',
		'{new0}Fraxos',
		'{new0}Esme',
		'{new0}Mako',
		'{new0}Myst',
		'Cas {number}',
		'{new0}Hedon',
		'{new0}Kelthuz',
		'{new2}Utoya',
		'{new0}Homer',
		'{new0}Alfheim',
		'{new0}Aurora',
		'{new0}Olympus',
		'{new0}Gomorrah',
		'{new0}Vidarr',
		'{new0}Vali',
		'{new0}Atlas',
		'{new0}Andromeda',
		'Hadar {number}',
		'Centauri {number}',
		'Rigel {number}',
		'Vega {number}',
		'Tau {number}',
		'Orionis {number}',
		'Tauri {number}',
		'Virginis {number}',
		'Leonis {number}',
		'Sirius {number}',
		'Sinistra {number}',
		'Capri {number}',
		'Pegasi {number}',
		'Herculis {number}',
		'Pollux {number}',
		'Sagittarii {number}',
		'Mira {number}',
		'Maia {number}',
		'Electra {number}',
		'Diadem {number}',
		'Ceti {number}',
		'Deneb {number}',
		'Castor {number}',
		'Betelgeuse {number}',
		'Asterion {number}',
		'Arcturus {number}',
		'Antares {number}',
		'Phoenix {number}',
		'Algol {number}',
		'Aldebaran {number}',
		'Cygni {number}',
		'Eri {number}',
		'Herschel {number}',
		'Barnard {number}',
		'Navi {number}',
		'Regor {number}',
		'Dnoces {number}',
]

earthlike = [	'{new2}Pompeii',
		'{new2}Ur',
		'{new2}Babylon',
		'{new2}Zanzibar',
		'{new2}Troy',
		'{new0}Utopia',
		'{new2}Somalia',
		'{new0}Corvin',
		'{new0}Rothbard',
		'{new0}Mises',
		'{new0}Atlantis',
		'{new0}Atlantis',
		'{new0}Numenor',
		'{new0}Camelot',
		'{new0}Ys',
		'{new2}Phoenicia',
		'{new0}Gaea',
]

desert = [	'{new0}Dune',
		'{new0}Sahara',
		'{new0}Gobi',
		'{new0}Mot',
		'{new0}Ereb',
		'New Mars',
		'{new0}Arrakis',
		'{new0}Karakum',
		'{new0}Kalahari',
		'{new0}Thar',
		'{new0}Nefud',
		'{new0}Ordos',
]

paradise = [	'{new0}Valhalla',
		'{new0}Eden',
		'{new0}Heaven',
		'{new0}Avalon',
		'{new0}Shangri-La',
		'{new0}Eldorado',
		'{new0}Hyperborea',
		'{new0}Lugnag',
		'{new0}Asgard',
		'{new0}Gimle',
		'{new0}Elysium',
		'New Earth',
		'{new0}Paradise',
]

ice = [		'{new1}Syberia',
		'{new1}Stalin',
		'{new0}Niflhel',
		'Snowball',
		'{new0}Amundsen',
		'{new0}Jotunheim',
		'{new0}Thule',
		'{new0}Utgard',
		'{new0}Helheim',
		'{new0}Ymir',
		'{new0}Polaris',
		'{new0}Arctica',
]

volcanic = [	'{new0}Hell',
		'{new0}Tartarus',
		'Fireball',
		'{new0}Ixion',
		'New Venus',
		'{new0}Surtur',
		'{new0}Muspelheim',
		'Draconis {number}',
		'{new0}Inferno',
		'{new0}Hephaistos',
]

water = [	'{new0}R\'lyeh',
		'{new0}Okeanos',
		'{new0}Triton',
		'{new0}Poseidon',
		'{new0}Ers',
		'{new0}Uls',
		'{new0}Init',
		'{new0}Aegir',
		'{new0}Yam',
		'Hydra',
]


if __name__ == '__main__':
    print 'works names'